package com.bw.movie;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.cinema.bean.UserInfoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO_BEAN".
*/
public class UserInfoBeanDao extends AbstractDao<UserInfoBean, Long> {

    public static final String TABLENAME = "USER_INFO_BEAN";

    /**
     * Properties of entity UserInfoBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Sid = new Property(0, long.class, "sid", true, "_id");
        public final static Property Birthday = new Property(1, long.class, "birthday", false, "BIRTHDAY");
        public final static Property Id = new Property(2, int.class, "id", false, "ID");
        public final static Property LastLoginTime = new Property(3, long.class, "lastLoginTime", false, "LAST_LOGIN_TIME");
        public final static Property NickName = new Property(4, String.class, "nickName", false, "NICK_NAME");
        public final static Property Phone = new Property(5, String.class, "phone", false, "PHONE");
        public final static Property Sex = new Property(6, int.class, "sex", false, "SEX");
        public final static Property HeadPic = new Property(7, String.class, "headPic", false, "HEAD_PIC");
        public final static Property Emails = new Property(8, String.class, "emails", false, "EMAILS");
        public final static Property SessionId = new Property(9, String.class, "sessionId", false, "SESSION_ID");
        public final static Property UserId = new Property(10, String.class, "userId", false, "USER_ID");
        public final static Property Pwd = new Property(11, String.class, "pwd", false, "PWD");
    }


    public UserInfoBeanDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: sid
                "\"BIRTHDAY\" INTEGER NOT NULL ," + // 1: birthday
                "\"ID\" INTEGER NOT NULL ," + // 2: id
                "\"LAST_LOGIN_TIME\" INTEGER NOT NULL ," + // 3: lastLoginTime
                "\"NICK_NAME\" TEXT," + // 4: nickName
                "\"PHONE\" TEXT," + // 5: phone
                "\"SEX\" INTEGER NOT NULL ," + // 6: sex
                "\"HEAD_PIC\" TEXT," + // 7: headPic
                "\"EMAILS\" TEXT," + // 8: emails
                "\"SESSION_ID\" TEXT," + // 9: sessionId
                "\"USER_ID\" TEXT," + // 10: userId
                "\"PWD\" TEXT);"); // 11: pwd
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfoBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getSid());
        stmt.bindLong(2, entity.getBirthday());
        stmt.bindLong(3, entity.getId());
        stmt.bindLong(4, entity.getLastLoginTime());
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(5, nickName);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(6, phone);
        }
        stmt.bindLong(7, entity.getSex());
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(8, headPic);
        }
 
        String emails = entity.getEmails();
        if (emails != null) {
            stmt.bindString(9, emails);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(10, sessionId);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(11, userId);
        }
 
        String pwd = entity.getPwd();
        if (pwd != null) {
            stmt.bindString(12, pwd);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfoBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getSid());
        stmt.bindLong(2, entity.getBirthday());
        stmt.bindLong(3, entity.getId());
        stmt.bindLong(4, entity.getLastLoginTime());
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(5, nickName);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(6, phone);
        }
        stmt.bindLong(7, entity.getSex());
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(8, headPic);
        }
 
        String emails = entity.getEmails();
        if (emails != null) {
            stmt.bindString(9, emails);
        }
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(10, sessionId);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(11, userId);
        }
 
        String pwd = entity.getPwd();
        if (pwd != null) {
            stmt.bindString(12, pwd);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public UserInfoBean readEntity(Cursor cursor, int offset) {
        UserInfoBean entity = new UserInfoBean( //
            cursor.getLong(offset + 0), // sid
            cursor.getLong(offset + 1), // birthday
            cursor.getInt(offset + 2), // id
            cursor.getLong(offset + 3), // lastLoginTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // nickName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // phone
            cursor.getInt(offset + 6), // sex
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // headPic
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // emails
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // sessionId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // userId
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // pwd
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfoBean entity, int offset) {
        entity.setSid(cursor.getLong(offset + 0));
        entity.setBirthday(cursor.getLong(offset + 1));
        entity.setId(cursor.getInt(offset + 2));
        entity.setLastLoginTime(cursor.getLong(offset + 3));
        entity.setNickName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPhone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSex(cursor.getInt(offset + 6));
        entity.setHeadPic(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEmails(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSessionId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setUserId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPwd(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserInfoBean entity, long rowId) {
        entity.setSid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserInfoBean entity) {
        if(entity != null) {
            return entity.getSid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInfoBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
